const FETCH_STORE_DETAIL_REQUEST = 'FETCH_STORE_DETAIL_REQUEST';
const FETCH_STORE_DETAIL_SUCCESS = 'FETCH_STORE_DETAIL_SUCCESS';
const FETCH_STORE_DETAIL_FAILED = 'FETCH_STORE_DETAIL_FAILED';

const FETCH_STORE_SPOTLIGHT_REQUEST = 'FETCH_STORE_SPOTLIGHT_REQUEST';
const FETCH_STORE_SPOTLIGHT_SUCCESS = 'FETCH_STORE_SPOTLIGHT_SUCCESS';
const FETCH_STORE_SPOTLIGHT_FAILED = 'FETCH_STORE_SPOTLIGHT_FAILED';

const SET_TAG_FILTER = 'SET_TAG_FILTER';
const TAG_POPULAR = 'popular'
const TAG_DEALS = 'deals'
const TAG_NEW_ARRIVAL = 'new_arrivals'

export default {
    FETCH_STORE_DETAIL_REQUEST,
    FETCH_STORE_DETAIL_SUCCESS,
    FETCH_STORE_DETAIL_FAILED,
    SET_TAG_FILTER,
    TAG_POPULAR,
    TAG_DEALS,
    TAG_NEW_ARRIVAL,
    FETCH_STORE_SPOTLIGHT_REQUEST,
    FETCH_STORE_SPOTLIGHT_SUCCESS,
    FETCH_STORE_SPOTLIGHT_FAILED
}