const FETCH_STORE_DETAIL_REQUEST = 'FETCH_STORE_DETAIL_REQUEST';
const FETCH_STORE_DETAIL_SUCCESS = 'FETCH_STORE_DETAIL_SUCCESS';
const FETCH_STORE_DETAIL_FAILED = 'FETCH_STORE_DETAIL_FAILED';

const FETCH_STORE_SPOTLIGHT_REQUEST = 'FETCH_STORE_SPOTLIGHT_REQUEST';
const FETCH_STORE_SPOTLIGHT_SUCCESS = 'FETCH_STORE_SPOTLIGHT_SUCCESS';
const FETCH_STORE_SPOTLIGHT_FAILED = 'FETCH_STORE_SPOTLIGHT_FAILED';

const SET_TAG = 'SET_TAG';

export default {
    FETCH_STORE_DETAIL_REQUEST,
    FETCH_STORE_DETAIL_SUCCESS,
    FETCH_STORE_DETAIL_FAILED,
    SET_TAG,
    FETCH_STORE_SPOTLIGHT_REQUEST,
    FETCH_STORE_SPOTLIGHT_SUCCESS,
    FETCH_STORE_SPOTLIGHT_FAILED
}